### ISSUE TITLE
Converted files have non-MST changes

### ISSUE THREAD

**Issue by praxxis** [mobxjs/mst-codemod-to-0.10#1]
For example, single quoted strings are changed to double quotes, and `import` statements have spaces added when they didn't exist before: 

<img width="406" alt="screenshot 2017-08-17 10 36 42" src="https://user-images.githubusercontent.com/15754/29417745-447607e4-8338-11e7-9ad0-be7fb5cbd2fa.png">

If this is a limitation of the TS compiler it's probably worth mentioning in the readme.

**Comment by mattiamanzati** [comment]
Yes, that's unfortunately a limitation of the TS code printer. It does'nt remeber the style of given code, just the AST.

I'll mention it in the readme! Thanks for your time!
